# Form implementation generated from reading ui file '.\stream\gui_launch\stream_execute.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(514, 463)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../img/logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 491, 441))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMinAndMaxSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputFile_LE = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.inputFile_LE.setObjectName("inputFile_LE")
        self.horizontalLayout.addWidget(self.inputFile_LE)
        self.inputFile_PB = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.inputFile_PB.setObjectName("inputFile_PB")
        self.horizontalLayout.addWidget(self.inputFile_PB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.outputDirectory_LE = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.outputDirectory_LE.setObjectName("outputDirectory_LE")
        self.horizontalLayout_2.addWidget(self.outputDirectory_LE)
        self.outputDirectory_PB = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.outputDirectory_PB.setObjectName("outputDirectory_PB")
        self.horizontalLayout_2.addWidget(self.outputDirectory_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.launchSimulation_PB = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.launchSimulation_PB.setObjectName("launchSimulation_PB")
        self.horizontalLayout_4.addWidget(self.launchSimulation_PB)
        self.stopSimulation_PB = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.stopSimulation_PB.setEnabled(False)
        self.stopSimulation_PB.setObjectName("stopSimulation_PB")
        self.horizontalLayout_4.addWidget(self.stopSimulation_PB)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 487, 306))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.logSimulation_TE = QtWidgets.QPlainTextEdit(parent=self.scrollAreaWidgetContents)
        self.logSimulation_TE.setGeometry(QtCore.QRect(0, 0, 861, 311))
        self.logSimulation_TE.setObjectName("logSimulation_TE")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stream"))
        self.label.setText(_translate("MainWindow", "Fichier de configuration"))
        self.inputFile_PB.setText(_translate("MainWindow", "Parcourir"))
        self.label_2.setText(_translate("MainWindow", "Dossier d\'enregistrement des résultats"))
        self.outputDirectory_PB.setText(_translate("MainWindow", "Parcourir"))
        self.launchSimulation_PB.setText(_translate("MainWindow", "Lancer la simulation"))
        self.stopSimulation_PB.setText(_translate("MainWindow", "Arrêter la simulation"))
